server:
  shutdown: immediate
spring:
  config:
    activate:
      on-profile: dev

  docker:
    compose:
      lifecycle-management: start-only   # 앱 종료 시 컨테이너를 stop하지 않음

  datasource:
    url: jdbc:postgresql://localhost:5432/mopl
    username: mopl
    password: mopl
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: mopl-dev
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

  web:
    resources:
      static-locations: classpath:/static/, file:./uploads/

opensearch:
  uris: http://localhost:9200

mopl:
  storage:
    local:
      base-url: http://localhost:8080
      upload-dir: ./uploads
  auth:
    cookie:
      secure: false
      same-site: Lax

logging:
  level:
    root: INFO
    com.codeit.team5.mopl: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.opensearch.client.RestClient: DEBUG
